views:
  - title: Sopbilen
    path: sopbilen
    icon: mdi:trash-can
    cards:
      - type: vertical-stack
        cards:
          - type: heading
            icon: phu:garbage-residual
            heading_style: title
            heading: Garbage Collection
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                entity: sensor.sopbilen_daltorpsvägen_28
                icon: mdi:trash-can
                name: Restavfall
                show_name: true
                show_state: false
                show_label: true
                label: |
                  [[[
                    const f = entity?.attributes?.fractions || {};
                    const frac = f['Restavfall, villa'];
                    if (!frac || !frac.execution_date) return '';

                    const d = new Date(frac.execution_date);
                    const today = new Date();
                    today.setHours(0,0,0,0);
                    const diff = Math.round((d - today) / 86400000);

                    if (diff === 0) return 'today';
                    if (diff === 1) return 'tomorrow';
                    if (diff > 1) return `${diff} days`;
                    return 'passed';
                  ]]]
                size: 40%
                tap_action:
                  action: more-info
                styles:
                  card:
                    - height: 100px
                    - width: 100px
                    - border-radius: 16px
                    - background-color: |
                        [[[
                          const f = entity?.attributes?.fractions || {};
                          const frac = f['Restavfall, villa'];
                          if (!frac || !frac.execution_date) return "#1c1c1c";

                          const d = new Date(frac.execution_date);
                          const today = new Date();
                          today.setHours(0,0,0,0);
                          const diff = Math.round((d - today) / 86400000);

                          // RED for today & tomorrow
                          if (diff === 0 || diff === 1) return "#b71c1c";

                          // YELLOW for 2–3 days left
                          if (diff === 2 || diff === 3) return "#fbc02d";

                          // default dark
                          return "#1c1c1c";
                        ]]]
                  icon:
                    - color: white
                  name:
                    - color: white
                    - font-size: 14px
                    - font-weight: bold
                    - justify-self: center
                  label:
                    - color: white
                    - font-size: 13px
                    - font-weight: bold
                    - justify-self: center
                    - align-self: end
                    - padding-bottom: 8px
              - type: custom:button-card
                entity: sensor.sopbilen_daltorpsvägen_28
                icon: mdi:food-apple-outline
                name: Matavfall
                show_name: true
                show_state: false
                show_label: true
                label: |
                  [[[
                    const f = entity?.attributes?.fractions || {};
                    const frac = f['Matavfall, villa'];
                    if (!frac || !frac.execution_date) return '';

                    const d = new Date(frac.execution_date);
                    const today = new Date();
                    today.setHours(0,0,0,0);
                    const diff = Math.round((d - today) / 86400000);

                    if (diff === 0) return 'today';
                    if (diff === 1) return 'tomorrow';
                    if (diff > 1) return `${diff} days`;
                    return 'passed';
                  ]]]
                size: 40%
                tap_action:
                  action: more-info
                styles:
                  card:
                    - height: 100px
                    - width: 100px
                    - border-radius: 16px
                    - background-color: |
                        [[[
                          const f = entity?.attributes?.fractions || {};
                          const frac = f['Matavfall, villa'];
                          if (!frac || !frac.execution_date) return "#1c1c1c";

                          const d = new Date(frac.execution_date);
                          const today = new Date();
                          today.setHours(0,0,0,0);
                          const diff = Math.round((d - today) / 86400000);

                          // RED for today & tomorrow
                          if (diff === 0 || diff === 1) return "#b71c1c";

                          // YELLOW for 2–3 days left
                          if (diff === 2 || diff === 3) return "#fbc02d";

                          return "#1c1c1c";
                        ]]]
                  icon:
                    - color: white
                  name:
                    - color: white
                    - font-size: 14px
                    - font-weight: bold
                    - justify-self: center
                  label:
                    - color: white
                    - font-size: 13px
                    - font-weight: bold
                    - justify-self: center
                    - align-self: end
                    - padding-bottom: 8px

